// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {codegen} from '../models';
import {model} from '../models';
import {convert} from '../models';

export function CodegenTargets():Promise<Array<codegen.Target>>;

export function ExportData(arg1:string,arg2:string):Promise<string>;

export function GenerateCode(arg1:string,arg2:model.HttpRequest):Promise<string>;

export function ImportCommit(arg1:string,arg2:convert.ImportResult):Promise<model.Node>;

export function ImportPreview(arg1:string,arg2:string):Promise<convert.ImportResult>;
