// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CodegenTargets() {
  return window['go']['binding']['ConvertApi']['CodegenTargets']();
}

export function ExportData(arg1, arg2) {
  return window['go']['binding']['ConvertApi']['ExportData'](arg1, arg2);
}

export function GenerateCode(arg1, arg2) {
  return window['go']['binding']['ConvertApi']['GenerateCode'](arg1, arg2);
}

export function ImportCommit(arg1, arg2) {
  return window['go']['binding']['ConvertApi']['ImportCommit'](arg1, arg2);
}

export function ImportPreview(arg1, arg2) {
  return window['go']['binding']['ConvertApi']['ImportPreview'](arg1, arg2);
}
