// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCookies(arg1) {
  return window['go']['binding']['CookieApi']['ClearCookies'](arg1);
}

export function DeleteCookie(arg1, arg2, arg3) {
  return window['go']['binding']['CookieApi']['DeleteCookie'](arg1, arg2, arg3);
}

export function ListCookies(arg1) {
  return window['go']['binding']['CookieApi']['ListCookies'](arg1);
}

export function UpsertCookie(arg1) {
  return window['go']['binding']['CookieApi']['UpsertCookie'](arg1);
}

export function UpsertCookies(arg1) {
  return window['go']['binding']['CookieApi']['UpsertCookies'](arg1);
}
