// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function ClearCookies(arg1:string):Promise<void>;

export function DeleteCookie(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ListCookies(arg1:string):Promise<Array<model.Cookie>>;

export function UpsertCookie(arg1:model.Cookie):Promise<void>;

export function UpsertCookies(arg1:Array<model.Cookie>):Promise<void>;
