// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDirectory(arg1) {
  return window['go']['binding']['DialogApi']['OpenDirectory'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['binding']['DialogApi']['OpenFile'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['binding']['DialogApi']['ReadTextFile'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['binding']['DialogApi']['SaveFile'](arg1, arg2);
}
