// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteEnvironment(arg1) {
  return window['go']['binding']['EnvApi']['DeleteEnvironment'](arg1);
}

export function GetGlobalVariables(arg1) {
  return window['go']['binding']['EnvApi']['GetGlobalVariables'](arg1);
}

export function ListEnvironments(arg1) {
  return window['go']['binding']['EnvApi']['ListEnvironments'](arg1);
}

export function SetActiveEnvironment(arg1, arg2) {
  return window['go']['binding']['EnvApi']['SetActiveEnvironment'](arg1, arg2);
}

export function SetGlobalVariables(arg1, arg2) {
  return window['go']['binding']['EnvApi']['SetGlobalVariables'](arg1, arg2);
}

export function UpsertEnvironment(arg1) {
  return window['go']['binding']['EnvApi']['UpsertEnvironment'](arg1);
}
