// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function DeleteEnvironment(arg1:string):Promise<void>;

export function GetGlobalVariables(arg1:string):Promise<Array<model.Variable>>;

export function ListEnvironments(arg1:string):Promise<Array<model.Environment>>;

export function SetActiveEnvironment(arg1:string,arg2:string):Promise<void>;

export function SetGlobalVariables(arg1:string,arg2:Array<model.Variable>):Promise<void>;

export function UpsertEnvironment(arg1:model.Environment):Promise<model.Environment>;
