// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteExample(arg1) {
  return window['go']['binding']['ExampleApi']['DeleteExample'](arg1);
}

export function ListExamples(arg1) {
  return window['go']['binding']['ExampleApi']['ListExamples'](arg1);
}

export function UpsertExample(arg1) {
  return window['go']['binding']['ExampleApi']['UpsertExample'](arg1);
}
