// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function DeleteExample(arg1:string):Promise<void>;

export function ListExamples(arg1:string):Promise<Array<model.Example>>;

export function UpsertExample(arg1:model.Example):Promise<model.Example>;
