// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {graphql} from '../models';

export function GraphqlIntrospect(arg1:graphql.IntrospectConfig):Promise<graphql.Result>;
