// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GraphqlIntrospect(arg1) {
  return window['go']['binding']['GraphqlApi']['GraphqlIntrospect'](arg1);
}
