// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GrpcCall(arg1, arg2, arg3, arg4) {
  return window['go']['binding']['GrpcApi']['GrpcCall'](arg1, arg2, arg3, arg4);
}

export function GrpcDiscover(arg1) {
  return window['go']['binding']['GrpcApi']['GrpcDiscover'](arg1);
}
