// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {grpcclient} from '../models';

export function GrpcCall(arg1:grpcclient.ConnectConfig,arg2:string,arg3:string,arg4:Record<string, string>):Promise<grpcclient.CallResult>;

export function GrpcDiscover(arg1:grpcclient.ConnectConfig):Promise<Array<grpcclient.MethodInfo>>;
