// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function ClearHistory(arg1:string):Promise<void>;

export function GetHistory(arg1:string,arg2:string):Promise<model.HistoryDetail>;

export function ListHistory(arg1:string,arg2:model.HistoryQuery):Promise<model.HistoryPage>;
