// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mock} from '../models';
import {binding} from '../models';

export function RunningMocks():Promise<Record<string, string>>;

export function StartMockServer(arg1:string,arg2:mock.Options):Promise<binding.MockStatus>;

export function StopMockServer(arg1:string):Promise<void>;
