// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunningMocks() {
  return window['go']['binding']['MockApi']['RunningMocks']();
}

export function StartMockServer(arg1, arg2) {
  return window['go']['binding']['MockApi']['StartMockServer'](arg1, arg2);
}

export function StopMockServer(arg1) {
  return window['go']['binding']['MockApi']['StopMockServer'](arg1);
}
