// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteNode(arg1) {
  return window['go']['binding']['NodeApi']['DeleteNode'](arg1);
}

export function GetDefaultWorkspace() {
  return window['go']['binding']['NodeApi']['GetDefaultWorkspace']();
}

export function ListNodes(arg1) {
  return window['go']['binding']['NodeApi']['ListNodes'](arg1);
}

export function MoveNode(arg1, arg2, arg3) {
  return window['go']['binding']['NodeApi']['MoveNode'](arg1, arg2, arg3);
}

export function UpsertNode(arg1) {
  return window['go']['binding']['NodeApi']['UpsertNode'](arg1);
}
