// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function DeleteNode(arg1:string):Promise<void>;

export function GetDefaultWorkspace():Promise<model.Workspace>;

export function ListNodes(arg1:string):Promise<Array<model.Node>>;

export function MoveNode(arg1:string,arg2:string,arg3:number):Promise<void>;

export function UpsertNode(arg1:model.Node):Promise<model.Node>;
