// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CreateWorkspace(arg1:string):Promise<model.Workspace>;

export function DeleteNode(arg1:string,arg2:string):Promise<void>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function GetDefaultWorkspace():Promise<model.Workspace>;

export function GetNode(arg1:string,arg2:string):Promise<model.Node>;

export function ListNodes(arg1:string):Promise<Array<model.NodeSummary>>;

export function ListWorkspaces():Promise<Array<model.Workspace>>;

export function MoveNode(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function MoveNodes(arg1:string,arg2:Array<model.NodeMove>):Promise<void>;

export function RenameNode(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameWorkspace(arg1:string,arg2:string):Promise<void>;

export function UpsertNode(arg1:model.Node):Promise<model.Node>;
