// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateWorkspace(arg1) {
  return window['go']['binding']['NodeApi']['CreateWorkspace'](arg1);
}

export function DeleteNode(arg1, arg2) {
  return window['go']['binding']['NodeApi']['DeleteNode'](arg1, arg2);
}

export function DeleteWorkspace(arg1) {
  return window['go']['binding']['NodeApi']['DeleteWorkspace'](arg1);
}

export function GetDefaultWorkspace() {
  return window['go']['binding']['NodeApi']['GetDefaultWorkspace']();
}

export function GetNode(arg1, arg2) {
  return window['go']['binding']['NodeApi']['GetNode'](arg1, arg2);
}

export function ListNodes(arg1) {
  return window['go']['binding']['NodeApi']['ListNodes'](arg1);
}

export function ListWorkspaces() {
  return window['go']['binding']['NodeApi']['ListWorkspaces']();
}

export function MoveNode(arg1, arg2, arg3, arg4) {
  return window['go']['binding']['NodeApi']['MoveNode'](arg1, arg2, arg3, arg4);
}

export function MoveNodes(arg1, arg2) {
  return window['go']['binding']['NodeApi']['MoveNodes'](arg1, arg2);
}

export function RenameNode(arg1, arg2, arg3) {
  return window['go']['binding']['NodeApi']['RenameNode'](arg1, arg2, arg3);
}

export function RenameWorkspace(arg1, arg2) {
  return window['go']['binding']['NodeApi']['RenameWorkspace'](arg1, arg2);
}

export function UpsertNode(arg1) {
  return window['go']['binding']['NodeApi']['UpsertNode'](arg1);
}
