// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';

export function ClearOAuth2Token(arg1:Record<string, string>):Promise<void>;

export function GetOAuth2Token(arg1:Record<string, string>):Promise<auth.Token>;
