// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearOAuth2Token(arg1) {
  return window['go']['binding']['OAuth2Api']['ClearOAuth2Token'](arg1);
}

export function GetOAuth2Token(arg1) {
  return window['go']['binding']['OAuth2Api']['GetOAuth2Token'](arg1);
}
