// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSession(arg1) {
  return window['go']['binding']['ProtocolApi']['CloseSession'](arg1);
}

export function OpenSession(arg1, arg2) {
  return window['go']['binding']['ProtocolApi']['OpenSession'](arg1, arg2);
}

export function SendMessage(arg1, arg2) {
  return window['go']['binding']['ProtocolApi']['SendMessage'](arg1, arg2);
}
