// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {protocol} from '../models';

export function CloseSession(arg1:string):Promise<void>;

export function OpenSession(arg1:string,arg2:protocol.SessionConfig):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;
