// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRequest(arg1) {
  return window['go']['binding']['RequestApi']['CancelRequest'](arg1);
}

export function GetResponseBlobInfo(arg1) {
  return window['go']['binding']['RequestApi']['GetResponseBlobInfo'](arg1);
}

export function ReadResponseBlobRange(arg1, arg2, arg3) {
  return window['go']['binding']['RequestApi']['ReadResponseBlobRange'](arg1, arg2, arg3);
}

export function ReleaseResponseBlob(arg1) {
  return window['go']['binding']['RequestApi']['ReleaseResponseBlob'](arg1);
}

export function SaveResponseBlob(arg1, arg2) {
  return window['go']['binding']['RequestApi']['SaveResponseBlob'](arg1, arg2);
}

export function SendRequest(arg1, arg2, arg3) {
  return window['go']['binding']['RequestApi']['SendRequest'](arg1, arg2, arg3);
}
