// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CancelRequest(arg1:string):Promise<void>;

export function GetResponseBlobInfo(arg1:string):Promise<model.ResponseBlobInfo>;

export function ReadResponseBlobRange(arg1:string,arg2:number,arg3:number):Promise<model.ResponseBlobChunk>;

export function ReleaseResponseBlob(arg1:string):Promise<void>;

export function SaveResponseBlob(arg1:string,arg2:string):Promise<number>;

export function SendRequest(arg1:string,arg2:model.HttpRequest,arg3:model.SendContext):Promise<model.ResponseResult>;
