// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {runner} from '../models';
import {model} from '../models';

export function CancelRun(arg1:string):Promise<void>;

export function ClearRunnerRuns(arg1:string):Promise<void>;

export function DeleteRunnerRun(arg1:string,arg2:string):Promise<void>;

export function ExportReport(arg1:string):Promise<string>;

export function ExportReportHTML(arg1:string):Promise<string>;

export function GetRunnerRun(arg1:string,arg2:string):Promise<runner.Report>;

export function ListRunnerRuns(arg1:string,arg2:model.RunnerRunQuery):Promise<model.RunnerRunPage>;

export function RunCollection(arg1:string,arg2:string,arg3:string,arg4:runner.Options):Promise<runner.Report>;
