// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {runner} from '../models';

export function CancelRun(arg1:string):Promise<void>;

export function ExportReport(arg1:string):Promise<string>;

export function RunCollection(arg1:string,arg2:string,arg3:string,arg4:runner.Options):Promise<runner.Report>;
