// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRun(arg1) {
  return window['go']['binding']['RunnerApi']['CancelRun'](arg1);
}

export function ExportReport(arg1) {
  return window['go']['binding']['RunnerApi']['ExportReport'](arg1);
}

export function RunCollection(arg1, arg2, arg3, arg4) {
  return window['go']['binding']['RunnerApi']['RunCollection'](arg1, arg2, arg3, arg4);
}
