// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {binding} from '../models';
import {httpengine} from '../models';
import {secrets} from '../models';
import {model} from '../models';

export function GetNetworkStatus():Promise<binding.NetworkStatus>;

export function GetProxySettings():Promise<binding.ProxySettings>;

export function GetRawSetting(arg1:string):Promise<string>;

export function GetTLSSettings():Promise<httpengine.TLSSettings>;

export function GetVaultStatus():Promise<secrets.Status>;

export function LockVault():Promise<secrets.Status>;

export function RefreshSystemProxy():Promise<binding.NetworkStatus>;

export function SetProxySettings(arg1:binding.ProxySettings):Promise<void>;

export function SetRawSetting(arg1:string,arg2:string):Promise<void>;

export function SetTLSSettings(arg1:httpengine.TLSSettings):Promise<void>;

export function StorageStats():Promise<model.StorageStats>;

export function UnlockVault(arg1:string):Promise<secrets.Status>;

export function VacuumDb():Promise<void>;
