// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProxySettings() {
  return window['go']['binding']['SettingsApi']['GetProxySettings']();
}

export function GetNetworkStatus() {
  return window['go']['binding']['SettingsApi']['GetNetworkStatus']();
}

export function GetTLSSettings() {
  return window['go']['binding']['SettingsApi']['GetTLSSettings']();
}

export function GetVaultStatus() {
  return window['go']['binding']['SettingsApi']['GetVaultStatus']();
}

export function LockVault() {
  return window['go']['binding']['SettingsApi']['LockVault']();
}

export function SetProxySettings(arg1) {
  return window['go']['binding']['SettingsApi']['SetProxySettings'](arg1);
}

export function SetTLSSettings(arg1) {
  return window['go']['binding']['SettingsApi']['SetTLSSettings'](arg1);
}

export function UnlockVault(arg1) {
  return window['go']['binding']['SettingsApi']['UnlockVault'](arg1);
}

export function RefreshSystemProxy() {
  return window['go']['binding']['SettingsApi']['RefreshSystemProxy']();
}
