// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {binding} from '../models';

export function GetProxySettings():Promise<binding.ProxySettings>;

export function SetProxySettings(arg1:binding.ProxySettings):Promise<void>;
