// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportDiagnostics(arg1) {
  return window['go']['binding']['SettingsApi']['ExportDiagnostics'](arg1);
}

export function GetNetworkStatus() {
  return window['go']['binding']['SettingsApi']['GetNetworkStatus']();
}

export function GetProxySettings() {
  return window['go']['binding']['SettingsApi']['GetProxySettings']();
}

export function GetRawSetting(arg1) {
  return window['go']['binding']['SettingsApi']['GetRawSetting'](arg1);
}

export function GetTLSSettings() {
  return window['go']['binding']['SettingsApi']['GetTLSSettings']();
}

export function GetVaultStatus() {
  return window['go']['binding']['SettingsApi']['GetVaultStatus']();
}

export function ListBackups() {
  return window['go']['binding']['SettingsApi']['ListBackups']();
}

export function LockVault() {
  return window['go']['binding']['SettingsApi']['LockVault']();
}

export function RecordStartup(arg1) {
  return window['go']['binding']['SettingsApi']['RecordStartup'](arg1);
}

export function RefreshSystemProxy() {
  return window['go']['binding']['SettingsApi']['RefreshSystemProxy']();
}

export function RunBackup() {
  return window['go']['binding']['SettingsApi']['RunBackup']();
}

export function SetProxySettings(arg1) {
  return window['go']['binding']['SettingsApi']['SetProxySettings'](arg1);
}

export function SetRawSetting(arg1, arg2) {
  return window['go']['binding']['SettingsApi']['SetRawSetting'](arg1, arg2);
}

export function SetTLSSettings(arg1) {
  return window['go']['binding']['SettingsApi']['SetTLSSettings'](arg1);
}

export function StartupMs() {
  return window['go']['binding']['SettingsApi']['StartupMs']();
}

export function StorageStats() {
  return window['go']['binding']['SettingsApi']['StorageStats']();
}

export function UnlockVault(arg1) {
  return window['go']['binding']['SettingsApi']['UnlockVault'](arg1);
}

export function VacuumDb() {
  return window['go']['binding']['SettingsApi']['VacuumDb']();
}
