// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {binding} from '../models';
import {httpengine} from '../models';

export function GetProxySettings():Promise<binding.ProxySettings>;

export function GetTLSSettings():Promise<httpengine.TLSSettings>;

export function SetProxySettings(arg1:binding.ProxySettings):Promise<void>;

export function SetTLSSettings(arg1:httpengine.TLSSettings):Promise<void>;
