// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sync} from '../models';
import {time} from '../models';

export function GetSyncConfig():Promise<sync.DavConfig>;

export function ImportRemoteWorkspace(arg1:string):Promise<sync.Report>;

export function ListRemoteWorkspaces():Promise<Array<sync.RemoteWorkspaceInfo>>;

export function SetSyncConfig(arg1:sync.DavConfig):Promise<void>;

export function StartAutoSync(arg1:time.Duration):Promise<any>;

export function SyncNow(arg1:string):Promise<sync.Report>;
