// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSyncConfig() {
  return window['go']['binding']['SyncApi']['GetSyncConfig']();
}

export function SetSyncConfig(arg1) {
  return window['go']['binding']['SyncApi']['SetSyncConfig'](arg1);
}

export function SyncNow(arg1) {
  return window['go']['binding']['SyncApi']['SyncNow'](arg1);
}
