// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sync} from '../models';

export function GetSyncConfig():Promise<sync.DavConfig>;

export function SetSyncConfig(arg1:sync.DavConfig):Promise<void>;

export function SyncNow(arg1:string):Promise<sync.Report>;
