// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyVerifiedUpdate() {
  return window['go']['binding']['UpdateApi']['ApplyVerifiedUpdate']();
}

export function CheckForUpdates() {
  return window['go']['binding']['UpdateApi']['CheckForUpdates']();
}
