// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';

export function ApplyVerifiedUpdate():Promise<updater.CheckResult>;

export function CheckForUpdates():Promise<updater.CheckResult>;
